### ISSUE TITLE
Error with "[error] Services cannot be empty"

### ISSUE THREAD

**Issue by nunofernandes** [vend/ecs-cleaner#2]
Hello,

I've just tried your program with the following command:
` docker run -ti -e AWS_REGION=eu-west-3 -e DEBUG='ecs-cleaner:*'  quay.io/vend/ecs-cleaner:latest ecs-task -v -v`

and it fails with:

```
  ecs-cleaner:index Starting ecs-cleaner CLI interface +0ms                                                                                       
[notice] Getting task definitions from AWS API                                  
  ecs-cleaner:api Getting clusters +112ms                                       
  ecs-cleaner:api Getting candidate task definitions +8ms first-page            
  ecs-cleaner:api Getting candidate task definitions +104ms paging              
  ecs-cleaner:api Listing services for cluster +6ms arn:aws:ecs:eu-west-3:XXXXXXXXX:cluster/workers-1 first-page
  ecs-cleaner:api Listing services for cluster +2ms arn:aws:ecs:eu-west-3:XXXXXXXXX:cluster/spot1 first-page
  ecs-cleaner:api Listing services for cluster +2ms arn:aws:ecs:eu-west-3:XXXXXXXXX:cluster/sauron-ingest first-page
  ecs-cleaner:api Listing services for cluster +2ms arn:aws:ecs:eu-west-3:XXXXXXXXX:cluster/components-0 first-page
  ecs-cleaner:api Getting candidate task definitions +55ms paging               
  ecs-cleaner:api Listing services for cluster +34ms arn:aws:ecs:eu-west-3:XXXXXXXXX:cluster/components-1 paging
[error] Services cannot be empty.                                               
[debug] InvalidParameterException: Services cannot be empty.                    
    at Request.extractError (/usr/src/app/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/request.js:668:14)   
    at Request.transition (/usr/src/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/src/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/src/app/node_modules/aws-sdk/lib/state_machine.js:26:10             
    at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/request.js:668:14)   
    at Request.transition (/usr/src/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/src/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/src/app/node_modules/aws-sdk/lib/state_machine.js:26:10             
    at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:38:9)
```

All ECS clusters have services. Here is the screenshot of the components-1 cluster (the last one in the above log).

![image](https://user-images.githubusercontent.com/1197165/45083640-46bb7800-b0f4-11e8-95d5-8b01d693af45.png)

Thanks for any help

**Comment by nunofernandes** [comment]
Any help on this? Thanks!

**Comment by santiagopoli** [comment]
I'm facing the same issue
